### ISSUE TITLE
error NETSDK1102 when build in .Net 9

### ISSUE THREAD

**Issue by drunkenQCat** [bytecodealliance/componentize-dotnet#49]
I edit my project following the instruction, but failed. The error message is just like this:
```
  wasiDotnet failed，thr (0.3 seconds) → bin\Debug\net9.0\wasi-wasm\wasiDotnet.dll
    C:\Users\Administrator\.nuget\packages\microsoft.net.illink.tasks\9.0.0-rc.1.24431.7\build\Microsoft.NET.ILLink.targets(207,5): error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app.
```

Until I added `<SelfContained>true</SelfContained>`.

**Comment by jsturtevant** [comment]
Thanks! we noticed this as well and have a staged pr in https://github.com/bytecodealliance/componentize-dotnet/pull/48 to add a comment. 

This is only need when using .net9 sdk

**Comment by jsturtevant** [comment]
should be updated in docs
