### ISSUE TITLE
Fix componentize-dotnet for Linux

### ISSUE THREAD

**Issue by jsturtevant** [bytecodealliance/componentize-dotnet#55]
Currently the package only pulls in the Windows version of the runtime packages:

```
runtime.win-x64.Microsoft.DotNet.ILCompiler.LLVM 
```

It should do this for the version that it is running against.  #54 is trying to solve that issue

## Workaround
The work around is is to add the package then run:

```
dotnet add runtime.linux-x64.Microsoft.DotNet.ILCompiler.LLVM 
```

**Comment by SingleAccretion** [comment]
As far as I am aware, there is no NuGet mechanism to pull in a RID-specific package based on the host (SDK's) RID.

(There is an undocumented mechanism for doing so with _target_ RIDs.)

I think the simplest way forward here is to make the SDK package itself RID-specific, i. e. publish:
```
BytecodeAlliance.Componentize.DotNet.WitBindgen.linux-x64
BytecodeAlliance.Componentize.DotNet.WitBindgen.win-x64
...
```
With the consumption side being:
```
<PackageReference Include="BytecodeAlliance.Componentize.DotNet.WitBindgen.$(NETCoreSdkPortableRuntimeIdentifier)" />
```
Then adding dependencies on RID-specific host tool packages becomes very simple.
