### ISSUE TITLE
Consuming wasm modules

### ISSUE THREAD

**Issue by furesoft** [bytecodealliance/componentize-dotnet#56]
Does this sdk helps consuming wasm modules on desktop apps?

**Comment by jsturtevant** [comment]
This project is meant to help produce wasi components in c#.

To consume the wasm modules from .net apps check out https://github.com/bytecodealliance/wasmtime-dotnet

**Comment by jsturtevant** [comment]
wasmtime-dotnet but it is blocked on the c-api in wasmtime: https://github.com/bytecodealliance/wasmtime-dotnet/issues/324
